## Neural Networks
- 궁극적인 인간의 꿈 : 컴퓨터가 인간을 대신해서 일을 해준다.
- 즉, Thinking Machine 을 생각하며 뇌를 연구했다.
- 생각보다 아주 복잡한 구조로 연결되어 있어서 놀랐다.
- 연결구조를 좀더 깊이 있게 보았더니 단순하게 동작하는데 또한번 놀랐다.
- 뉴런이 연결되어 있으면 활성화가 되었고, 연결되어 있지않으면 비활성화로 되어 있어, 
- 이정도면 구현가능하겠다는 생각으로 Neural Networks를 구현하기 시작하였다. 
- → 이것이 초창기의 '인공지능' 이었다.

### Xor.py

In [1]:
# XOR, This example does not work
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

# cost/loss function   cf.Sigmoid
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

C:\Python\Anaconda3-52\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
sess = tf.Session()
# Initialize TensorFlow variables
sess.run(tf.global_variables_initializer())

for step in range(10001):
    sess.run(train, feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0:
        print("\nstep: {step}, \nsess.run(cost, feed_dict[X: x_data, Y: y_data]): {run_cost}, \nsess.run(W): \n{run_weight}".format(
                step = step, 
                run_cost = sess.run(cost, feed_dict={X: x_data, Y: y_data}), 
                run_weight = sess.run(W)
            ))


step: 0, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.8759795427322388, 
sess.run(W): 
[[0.7863567]
 [0.6628261]]

step: 1000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.693149209022522, 
sess.run(W): 
[[0.00566576]
 [0.00542594]]

step: 2000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.6931471824645996, 
sess.run(W): 
[[0.00010905]
 [0.0001086 ]]

step: 3000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.6931471824645996, 
sess.run(W): 
[[2.1300866e-06]
 [2.1307264e-06]]

step: 4000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.6931471824645996, 
sess.run(W): 
[[1.3183484e-07]
 [1.3247467e-07]]

step: 5000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.6931471824645996, 
sess.run(W): 
[[1.3183484e-07]
 [1.3247467e-07]]

step: 6000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.6931471824645996, 
sess.run(W): 
[[1.3183484e-07]
 [1.3247467e-07]]

step: 7000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.6931471824645996, 
sess.run(

In [4]:
# Accuracy report
h, c, a = sess.run([hypothesis, predicted, accuracy],
                   feed_dict={X: x_data, Y: y_data})
print("\nHypothesis: \n{h} \n\nCorrect: \n{c} \n\nAccuracy: {a}".format(
        h=h, c=c, a=a
    ))


Hypothesis: 
[[0.5]
 [0.5]
 [0.5]
 [0.5]] 

Correct: 
[[0.]
 [0.]
 [0.]
 [0.]] 

Accuracy: 0.5


### xor-nn.py
- 해결

In [5]:
# XOR using NN
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [6]:
sess = tf.Session()

# Initialize TensorFlow variables
sess.run(tf.global_variables_initializer())

for step in range(10001):
    sess.run(train, feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0:
        # print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run([W1, W2]))
        print("\nstep: {step}, \nsess.run(cost, feed_dict[X: x_data, Y: y_data]): {run_cost}, \nsess.run([W1, W2]): \n{run_weight}".format(
                step = step, 
                run_cost = sess.run(cost, feed_dict={X: x_data, Y: y_data}), 
                run_weight = sess.run([W1, W2])
            ))


step: 0, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 1.199636459350586, 
sess.run([W1, W2]): 
[array([[-0.2585768, -1.6877581],
       [ 0.7953152, -1.8291923]], dtype=float32), array([[-0.19314797],
       [ 0.26608956]], dtype=float32)]

step: 1000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.6310248374938965, 
sess.run([W1, W2]): 
[array([[ 0.4179597, -2.3734052],
       [ 0.7820524, -2.4259977]], dtype=float32), array([[ 0.8679456],
       [-1.857622 ]], dtype=float32)]

step: 2000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.5447923541069031, 
sess.run([W1, W2]): 
[array([[ 0.6924966 , -3.8657207 ],
       [ 0.85429245, -3.8673575 ]], dtype=float32), array([[ 0.7114396],
       [-3.745849 ]], dtype=float32)]

step: 3000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.5117793083190918, 
sess.run([W1, W2]): 
[array([[ 0.7856119 , -4.8194876 ],
       [ 0.89650464, -4.817776  ]], dtype=float32), array([[ 0.42635164],
       [-4.7837334 ]], dtype=float32)]


In [7]:
# Accuracy report
h, c, a = sess.run([hypothesis, predicted, accuracy],
                   feed_dict={X: x_data, Y: y_data})
print("\nHypothesis: \n{h} \n\nCorrect: \n{c} \n\nAccuracy: {a}".format(
        h=h, c=c, a=a
    ))


Hypothesis: 
[[0.03051938]
 [0.927457  ]
 [0.92743737]
 [0.09300204]] 

Correct: 
[[0.]
 [1.]
 [1.]
 [0.]] 

Accuracy: 1.0


### Xor-nn-wide-deep.py

In [10]:
# XOR-NN-Wide-Deep
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([10, 1]), name='weight4')
b4 = tf.Variable(tf.random_normal([1]), name='bias4')
hypothesis = tf.sigmoid(tf.matmul(layer3, W4) + b4)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# 레이어 과다사용시 되려 정확도가 떨어짐
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([10, 10]), name='weight4')
b4 = tf.Variable(tf.random_normal([10]), name='bias4')
layer4 = tf.sigmoid(tf.matmul(layer3, W4) + b4)

W5 = tf.Variable(tf.random_normal([10, 10]), name='weight5')
b5 = tf.Variable(tf.random_normal([10]), name='bias5')
layer5 = tf.sigmoid(tf.matmul(layer4, W5) + b5)

W6 = tf.Variable(tf.random_normal([10, 10]), name='weight6')
b6 = tf.Variable(tf.random_normal([10]), name='bias6')
layer6 = tf.sigmoid(tf.matmul(layer5, W6) + b6)

W7 = tf.Variable(tf.random_normal([10, 10]), name='weight7')
b7 = tf.Variable(tf.random_normal([10]), name='bias7')
layer7 = tf.sigmoid(tf.matmul(layer6, W7) + b7)

W8 = tf.Variable(tf.random_normal([10, 10]), name='weight8')
b8 = tf.Variable(tf.random_normal([10]), name='bias8')
layer8 = tf.sigmoid(tf.matmul(layer7, W8) + b8)

W9 = tf.Variable(tf.random_normal([10, 10]), name='weight9')
b9 = tf.Variable(tf.random_normal([10]), name='bias9')
layer9 = tf.sigmoid(tf.matmul(layer8, W9) + b9)

W10 = tf.Variable(tf.random_normal([10, 1]), name='weight10')
b10 = tf.Variable(tf.random_normal([1]), name='bias10')
hypothesis = tf.sigmoid(tf.matmul(layer9, W10) + b10)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [11]:
sess = tf.Session()

# Initialize TensorFlow variables
sess.run(tf.global_variables_initializer())

for step in range(10001):
    sess.run(train, feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0:
        # print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run([W1, W2]))
        print("\nstep: {step}, \nsess.run(cost, feed_dict[X: x_data, Y: y_data]): {run_cost}, \nsess.run([W1, W2]): \n{run_weight}".format(
                step = step, 
                run_cost = sess.run(cost, feed_dict={X: x_data, Y: y_data}), 
                run_weight = sess.run([W1, W2])
            ))


step: 0, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.702400267124176, 
sess.run([W1, W2]): 
[array([[ 0.6969371 ,  1.1588397 ,  0.6702637 ,  0.8843343 , -0.14518431,
        -0.7319982 , -0.04773948, -1.1376959 , -0.06045236, -0.9886378 ],
       [-1.82135   ,  0.45490947, -0.01658978,  0.01832741, -0.53659946,
        -0.07823775,  0.3294301 ,  0.03019173, -0.10301708,  0.06603207]],
      dtype=float32), array([[-0.50563467, -1.0618674 , -0.42291433,  0.2586453 , -0.5319152 ,
         1.0188215 , -1.8282285 ,  0.7547538 , -0.13720454,  0.17663701],
       [-1.1992528 , -1.8915216 ,  0.3279002 ,  0.2975171 ,  0.56828123,
         0.03508321,  0.17001775,  1.5818249 ,  0.8378167 ,  1.1636909 ],
       [ 0.38002738, -1.0578125 , -1.4519527 ,  1.2230562 , -1.6177012 ,
        -0.77383536,  1.9716059 , -0.27862662, -0.64313257,  0.40237394],
       [ 0.14204286,  0.4316682 , -0.36919153, -0.16944349,  0.9727236 ,
        -0.8401676 , -0.27421546,  2.6554363 ,  0.46321657,  1.6213


step: 5000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.0038556926883757114, 
sess.run([W1, W2]): 
[array([[ 3.2836275 ,  1.2253077 ,  0.8877057 ,  1.262504  , -3.1041822 ,
        -0.96493685, -0.01908156, -1.4844985 , -0.07121085, -3.4782255 ],
       [-4.5170417 ,  0.8156644 , -0.39699194, -0.19665872, -3.5448356 ,
        -0.2516924 ,  0.33797982,  0.06621362,  0.26563233,  1.5902953 ]],
      dtype=float32), array([[-2.2714317 , -1.0867995 , -0.4468241 ,  0.44376484, -2.0673828 ,
         0.76441425, -3.9218287 ,  0.75752467,  0.1343633 ,  0.77187455],
       [-1.1337389 , -1.9028429 ,  0.33213007,  0.1628737 ,  0.27089137,
        -0.09653755, -0.23735736,  1.5717763 ,  0.83236253,  0.79211754],
       [ 0.7184548 , -1.0639224 , -1.4479401 ,  1.0923327 , -1.6616625 ,
        -0.89627534,  1.8867801 , -0.2838305 , -0.6817062 , -0.00573223],
       [ 0.75051415,  0.44225937, -0.36487654, -0.26788944,  1.294914  ,
        -0.9533803 ,  0.17607322,  2.6654174 ,  0.32431674, 


step: 10000, 
sess.run(cost, feed_dict[X: x_data, Y: y_data]): 0.0012195772724226117, 
sess.run([W1, W2]): 
[array([[ 3.4403610e+00,  1.2304416e+00,  9.1584396e-01,  1.3104964e+00,
        -3.2439957e+00, -9.9567896e-01, -2.4812492e-03, -1.5592937e+00,
        -5.8995474e-02, -3.6908622e+00],
       [-4.6918726e+00,  8.2460481e-01, -4.1540396e-01, -1.8478067e-01,
        -3.6515121e+00, -2.7449098e-01,  3.3792520e-01,  8.2495511e-02,
         3.1387144e-01,  1.7770131e+00]], dtype=float32), array([[-2.4887083 , -1.0873508 , -0.44550142,  0.46910015, -2.2006419 ,
         0.7496183 , -4.106364  ,  0.7572912 ,  0.18152371,  0.8941226 ],
       [-1.1238799 , -1.9042827 ,  0.33117947,  0.1418127 ,  0.27557057,
        -0.1050474 , -0.22085921,  1.5719132 ,  0.83157986,  0.77233815],
       [ 0.7388403 , -1.0650051 , -1.4487809 ,  1.072995  , -1.6426921 ,
        -0.90463823,  1.921582  , -0.28358775, -0.68396723, -0.03160251],
       [ 0.78467447,  0.4420615 , -0.36552662, -0.28167906,  1

In [12]:
# Accuracy report
h, c, a = sess.run([hypothesis, predicted, accuracy],
                   feed_dict={X: x_data, Y: y_data})
# print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)
print("\nHypothesis: \n{h} \n\nCorrect: \n{c} \n\nAccuracy: {a}".format(
        h=h, c=c, a=a
    ))


Hypothesis: 
[[7.4904622e-04]
 [9.9866307e-01]
 [9.9866891e-01]
 [1.4581166e-03]] 

Correct: 
[[0.]
 [1.]
 [1.]
 [0.]] 

Accuracy: 1.0
