### Tensor Manipulation

In [1]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint

tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

C:\Python\Anaconda3-52\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


### Simple Array

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)

array([0., 1., 2., 3., 4., 5., 6.])


In [3]:
t.ndim

1

In [4]:
t.shape

(7,)

In [5]:
t[0], t[1], t[-1]

(0.0, 1.0, 6.0)

### 2D Array

In [6]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
t

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [7]:
t.ndim

2

In [8]:
t.shape

(4, 3)

### Shape, Rank, Axis

In [9]:
t = tf.constant([1,2,3,4])

In [10]:
tf.shape(t)

<tf.Tensor 'Shape:0' shape=(1,) dtype=int32>

In [11]:
tf.shape(t).eval()

array([4])

In [12]:
t.shape

TensorShape([Dimension(4)])

In [13]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [14]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [15]:
t.eval()

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]])

In [16]:
[
    [
        [
            [1, 2, 3, 4], 
            [5, 6, 7, 8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

### Matmul VS multiply 
- matrix1 = [ [3, 3] ]
- matrix2 = [ [2],[2] ]

In [22]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

In [23]:
matrix1.shape

TensorShape([Dimension(1), Dimension(2)])

In [24]:
matrix2.shape

TensorShape([Dimension(2), Dimension(1)])

#### matmul : M(1, 2) • M(2, 1) = M(1, 1)

In [25]:
tf.matmul(matrix1, matrix2).eval()

array([[12.]], dtype=float32)

#### multiply : M(1, 2) x M(2, 1) = M(2, 2)

In [26]:
(matrix1*matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

### Watch out broadcasting

#### M(1, 2) + M(2, 1) = M(2, 2)

In [27]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [28]:
matrix1.shape

TensorShape([Dimension(1), Dimension(2)])

In [29]:
matrix2.shape

TensorShape([Dimension(2), Dimension(1)])

## Random values for variable initializations 
- tf.random_normal
- tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)

- Outputs random values from a normal distribution.
- A tensor of the specified shape filled with random normal values.

In [30]:
tf.random_normal([3]).eval()

array([-1.0997633,  1.3392986, -0.6582208], dtype=float32)

In [31]:
tf.random_normal([3], mean=5, stddev=2.5).eval()

array([3.7257605, 6.4580884, 5.795608 ], dtype=float32)

### Reduce Mean/Sum 

In [32]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [33]:
x = [[1., 2.],
     [3., 4.]]

In [34]:
tf.reduce_mean(x).eval()

2.5

In [35]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [36]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [37]:
tf.reduce_sum(x).eval()

10.0

In [38]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [39]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [40]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

### Reshape, squeeze, expand_dims

#### tf.reshape
- Reshapes a tensor.

- If one component of shape is the special value -1, the size of that dimension is computed so that the total size remains constant. 
- In particular, a shape of [-1] flattens into 1-D. At most one component of shape can be -1. 

- If shape is 1-D or higher, then the operation returns a tensor with shape shape filled with the values of tensor. 
- In this case, the number of elements implied by shape must be the same as the number of elements in tensor.

In [17]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [18]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

### tf.squeeze
- tf.squeeze(input, axis=None, name=None, squeeze_dims=None)

- Removes dimensions of size 1 from the shape of a tensor.

In [20]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

### tf.expand_dims
- tf.expand_dims(input, axis=None, name=None, dim=None)

- Inserts a dimension of 1 into a tensor's shape.

In [21]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

### One hot 
- tf.expand_dims
- tf.one_hot(indices, depth, on_value=None, off_value=None, axis=None, dtype=None, name=None)

- Returns a one-hot tensor.
- indices: A Tensor of indices.
- depth: A scalar defining the depth of the one hot dimension.
- on_value: A scalar defining the value to fill in output when indices[j] = i. (default: 1)
- off_value: A scalar defining the value to fill in output when indices[j] != i. (default: 0)
- axis: The axis to fill (default: -1, a new inner-most axis).
- dtype: The data type of the output tensor.

In [41]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [42]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

### Casting 
- tf.cast
- tf.cast(x, dtype, name=None)

- Casts a tensor to a new type.
- x: A Tensor or SparseTensor.
- dtype: The destination type.
- name: A name for the operation (optional).

In [43]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [44]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

### Stack 
- tf.stack
- tf.stack(values, axis=0, name='stack')

- Stacks a list of rank-R tensors into one rank-(R+1) tensor.
- Packs the list of tensors in values into a tensor with rank one higher than each tensor in values, by packing them along the axis dimension. Given a list of length N of tensors of shape (A, B, C); 
- if axis == 0 then the output tensor will have the shape (N, A, B, C). 
- if axis == 1 then the output tensor will have the shape (A, N, B, C).

In [46]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

In [47]:
# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

### Ones like and Zeros like

In [49]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [50]:
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [51]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

### Zip 

In [52]:
for something in zip([1, 2, 3], [4, 5, 6]):
    print(something)

(1, 4)
(2, 5)
(3, 6)


In [53]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [54]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


### Transpose 
- tf.transpose
- tf.transpose(a, perm=None, name='transpose')

- Transposes a. Permutes the dimensions according to perm.
- a: A Tensor.
- perm: A permutation of the dimensions of a.
- name: A name for the operation (optional).

In [55]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [56]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [57]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [58]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [59]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
